const i18n = {
    'zh-cn': {
        title: "知识花园",
        subtitle: "输入想法或链接，AI 园丁将为您自动培育知识",
        inputPlaceholder: "例如：量子纠缠的非局域性特征...",
        inputLabel: "输入内容...",
        btnSubmit: "开始培育 (Sow Seeds)",
        navSow: "播种灵感",
        navGarden: "查看花园",
        navSettings: "系统设置",
        footerCopy: "© 2026 知识花园 AI 项目",
        agent1: "Agent 1 (Ingestion): 正在总结内容...",
        agent2: "Agent 2 (Synthesis): 发现知识隐藏关联...",
        agent3: "Agent 3 (Growth): 催生复习建议...",
        btnExport: "导出备份",
        btnImport: "导入备份",
        btnClear: "清空花园",

        emptyInput: "请输入内容后再播种哦！",
        fetchError: "网络或系统解析错误，请检查后端服务。",
        backendErrorTitle: "培育失败 (Backend Error)",
        backendErrorHint: "请按 F12 在控制台查看详细堆栈。",
        importSuccess: "导入成功！已合并数据。",
        invalidFile: "非法文件格式！",
        confirmClear: "确定要拔掉所有的知识植物吗？此操作不可撤销。",
        emptyGarden: "花园还是空的。",
        goSow: "去播种"
    },

    'zh-tw': {
        title: "知識花園",
        subtitle: "輸入想法或連結，AI 園丁將為您自動培育知識",
        inputPlaceholder: "例如：量子糾纏的非局域性特徵...",
        inputLabel: "輸入內容...",
        btnSubmit: "開始培育 (Sow Seeds)",
        navSow: "播種靈感",
        navGarden: "查看花園",
        navSettings: "系統設置",
        footerCopy: "© 2026 知識花園 AI 項目",
        agent1: "Agent 1 (Ingestion): 正在總結內容...",
        agent2: "Agent 2 (Synthesis): 發現知識隱藏關聯...",
        agent3: "Agent 3 (Growth): 催生複習建議...",
        btnExport: "導出備份",
        btnImport: "導入備份",
        btnClear: "清空花園",

        emptyInput: "請先輸入內容再播種哦！",
        fetchError: "網路或系統解析錯誤，請檢查後端服務。",
        backendErrorTitle: "培育失敗 (Backend Error)",
        backendErrorHint: "請按 F12 在控制台查看詳細堆疊。",
        importSuccess: "導入成功！已合併資料。",
        invalidFile: "非法檔案格式！",
        confirmClear: "確定要拔掉所有的知識植物嗎？此操作不可撤銷。",
        emptyGarden: "花園還是空的。",
        goSow: "去播種"
    },

    'en': {
        title: "Knowledge Garden",
        subtitle: "Enter ideas or links, and AI gardeners will automatically cultivate knowledge for you",
        inputPlaceholder: "e.g., Non-local characteristics of quantum entanglement...",
        inputLabel: "Input Content...",
        btnSubmit: "Sow Seeds",
        navSow: "Sow Inspiration",
        navGarden: "View Garden",
        navSettings: "Settings",
        footerCopy: "© 2026 Knowledge Garden AI Project",
        agent1: "Agent 1 (Ingestion): Summarizing content...",
        agent2: "Agent 2 (Synthesis): Discovering hidden connections...",
        agent3: "Agent 3 (Growth): Generating growth suggestions...",
        btnExport: "Export Backup",
        btnImport: "Import Backup",
        btnClear: "Clear Garden",

        emptyInput: "Please enter something before sowing.",
        fetchError: "Network or system parsing error. Please check the backend service.",
        backendErrorTitle: "Cultivation Failed (Backend Error)",
        backendErrorHint: "Press F12 to view the detailed stack trace in the console.",
        importSuccess: "Import successful! Data has been merged.",
        invalidFile: "Invalid file format!",
        confirmClear: "Are you sure you want to remove all knowledge plants? This action cannot be undone.",
        emptyGarden: "Garden is empty.",
        goSow: "Go Sow"
    }
};
