const i18n = {
  'zh-cn': {
    title: "知识花园",
    subtitle: "输入想法或链接，AI 园丁将为您自动培育知识",
    inputPlaceholder: "例如：量子纠缠的非局域性特征...",
    inputLabel: "输入内容...",
    btnSubmit: "开始培育 (Sow Seeds)",
    navSow: "播种灵感",
    navGarden: "查看花园",
    navSettings: "系统设置",
    footerCopy: "© 2026 知识花园 AI 项目",

    agent1: "Agent 1 (Ingestion): 正在总结内容...",
    agent2: "Agent 2 (Synthesis): 发现知识隐藏关联...",
    agent3: "Agent 3 (Growth): 催生新想法与生长方向...",

    btnExport: "导出备份",
    btnImport: "导入备份",
    btnClear: "清空花园",

    emptyInput: "请输入内容后再播种哦！",
    fetchError: "网络或系统解析错误，请检查后端服务。",
    backendErrorTitle: "培育失败 (Backend Error)",
    backendErrorHint: "请按 F12 在控制台查看详细堆栈。",
    importSuccess: "导入成功！已合并数据。",
    invalidFile: "非法文件格式！",
    confirmClear: "确定要拔掉所有的知识植物吗？此操作不可撤销。",
    emptyGarden: "花园还是空的。",
    goSow: "去播种",

    gardenEmpty: "花园还是空的。",
    gardenExport: "导出备份",
    gardenImport: "导入备份",
    gardenClear: "清空花园",
    gardenRefreshEmpty: "花园为空",
    gardenRefreshCount: "已刷新，共 {count} 株知识植物",
    gardenExportDone: "备份已导出",
    gardenImportSuccess: "导入成功，已合并数据。",
    gardenInvalidFile: "非法文件格式！",
    gardenClearConfirm: "确定要拔掉所有的知识植物吗？此操作不可撤销。",
    gardenClearDone: "花园已清空",
    gardenUntitled: "未命名知识",
    confirmDelete: "确定要从花园中铲除这个灵感吗？此操作不可撤销。",
    deleteDone: "灵感已铲除",
    copySuccess: "内容已复制到剪贴板",
    copyError: "复制失败，请手动选择复制",
    btnCopy: "复制内容",
    btnDelete: "删除灵感",
    btnCombine: "整合 {count} 个想法",
    btnGeneratePPT: "生成演示大纲",
    pptHeadline: "演示大纲 (Marp Markdown)",
    copyMarp: "复制 Markdown",
    combineLoading: "正在融合见解...",
    combineSuccess: "新混合种子已诞生！",
  },

  'zh-tw': {
    title: "知識花園",
    subtitle: "輸入想法或連結，AI 園丁將為您自動培育知識",
    inputPlaceholder: "例如：量子糾纏的非局域性特徵...",
    inputLabel: "輸入內容...",
    btnSubmit: "開始培育 (Sow Seeds)",
    navSow: "播種靈感",
    navGarden: "查看花園",
    navSettings: "系統設置",
    footerCopy: "© 2026 知識花園 AI 項目",

    agent1: "Agent 1 (Ingestion): 正在總結內容...",
    agent2: "Agent 2 (Synthesis): 發現知識隱藏關聯...",
    agent3: "Agent 3 (Growth): 催生新想法與成長方向...",

    btnExport: "導出備份",
    btnImport: "導入備份",
    btnClear: "清空花園",

    emptyInput: "請先輸入內容再播種哦！",
    fetchError: "網路或系統解析錯誤，請檢查後端服務。",
    backendErrorTitle: "培育失敗 (Backend Error)",
    backendErrorHint: "請按 F12 在控制台查看詳細堆疊。",
    importSuccess: "導入成功！已合併資料。",
    invalidFile: "非法檔案格式！",
    confirmClear: "確定要拔掉所有的知識植物嗎？此操作不可撤銷。",
    emptyGarden: "花園還是空的。",
    goSow: "去播種",

    gardenEmpty: "花園還是空的。",
    gardenExport: "匯出備份",
    gardenImport: "匯入備份",
    gardenClear: "清空花園",
    gardenRefreshEmpty: "花園為空",
    gardenRefreshCount: "已重新整理，目前共有 {count} 株知識植物",
    gardenExportDone: "備份已匯出",
    gardenImportSuccess: "匯入成功，已合併資料。",
    gardenInvalidFile: "非法檔案格式！",
    gardenClearConfirm: "確定要拔掉所有知識植物嗎？此操作無法撤銷。",
    gardenClearDone: "花園已清空",
    gardenUntitled: "未命名知識",
    confirmDelete: "確定要從花園中鏟除這個靈感嗎？此操作不可撤銷。",
    deleteDone: "靈感已鏟除",
    copySuccess: "內容已複製到剪貼簿",
    copyError: "複製失敗，請手動選擇複製",
    btnCopy: "複製內容",
    btnDelete: "刪除靈感",
    btnCombine: "整合 {count} 個想法",
    btnGeneratePPT: "生成演示大綱",
    pptHeadline: "演示大綱 (Marp Markdown)",
    copyMarp: "複製 Markdown",
    combineLoading: "正在融合見解...",
    combineSuccess: "新混合種子已誕生！"
  },

  'en': {
    title: "Knowledge Garden",
    subtitle: "Enter ideas or links, and AI gardeners will automatically cultivate knowledge for you",
    inputPlaceholder: "e.g., Non-local characteristics of quantum entanglement...",
    inputLabel: "Input Content...",
    btnSubmit: "Sow Seeds",
    navSow: "Sow Inspiration",
    navGarden: "View Garden",
    navSettings: "Settings",
    footerCopy: "© 2026 Knowledge Garden AI Project",

    agent1: "Agent 1 (Ingestion): Summarizing content...",
    agent2: "Agent 2 (Synthesis): Discovering hidden connections...",
    agent3: "Agent 3 (Growth): Generating new ideas and growth paths...",

    btnExport: "Export Backup",
    btnImport: "Import Backup",
    btnClear: "Clear Garden",

    emptyInput: "Please enter something before sowing.",
    fetchError: "Network or system parsing error. Please check the backend service.",
    backendErrorTitle: "Cultivation Failed (Backend Error)",
    backendErrorHint: "Press F12 to view the detailed stack trace in the console.",
    importSuccess: "Import successful! Data has been merged.",
    invalidFile: "Invalid file format!",
    confirmClear: "Are you sure you want to remove all knowledge plants? This action cannot be undone.",
    emptyGarden: "Garden is empty.",
    goSow: "Go Sow",

    gardenEmpty: "Garden is empty.",
    gardenExport: "Export Backup",
    gardenImport: "Import Backup",
    gardenClear: "Clear Garden",
    gardenRefreshEmpty: "Garden is empty",
    gardenRefreshCount: "Refreshed. {count} knowledge plants loaded.",
    gardenExportDone: "Backup exported",
    gardenImportSuccess: "Import successful. Data merged.",
    gardenInvalidFile: "Invalid file format!",
    gardenClearConfirm: "Are you sure you want to clear all plants? This action cannot be undone.",
    gardenClearDone: "Garden cleared",
    gardenUntitled: "Untitled Knowledge",
    confirmDelete: "Are you sure you want to remove this inspiration? This action cannot be undone.",
    deleteDone: "Inspiration removed",
    copySuccess: "Copied to clipboard",
    copyError: "Copy failed, please copy manually",
    btnCopy: "Copy Content",
    btnDelete: "Delete Inspiration",
    btnCombine: "整合 {count} 个想法",
    btnGeneratePPT: "生成演示大纲",
    pptHeadline: "演示大纲 (Marp Markdown)",
    copyMarp: "复制 Markdown",
    combineLoading: "正在融合见解...",
    combineSuccess: "新混合种子已诞生！",
    confirmDelete: "确定要删除这条灵感吗？",
    copySuccess: "已复制到剪贴板",
    btnCombine: "Combine {count} Seeds",
    btnGeneratePPT: "Generate PPT",
    pptHeadline: "Presentation Outline (Marp)",
    copyMarp: "Copy Markdown",
    combineLoading: "Fusing insights...",
    combineSuccess: "New Hybrid Seed Created!"
  }
};
